### ISSUE TITLE
Cannot find module 'harp'

### ISSUE THREAD

**Issue by greenthoms** [superhighfives/harp-gulp-browsersync-boilerplate#3]
After installing and running I gulp I get the following error:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'harp'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Thomas/Dropbox/Vocation/code/src/gulpfile.js:4:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by superhighfives** [comment]
Hmm, that's not good! Sorry for the late reply. Have you installed harp with `npm install -g harp`?
